# version: "3"

services:
  react:
    build:
      context: .
      dockerfile: ./client-pong/Dockerfile
    container_name: react
    ports:
      - "5173:5173"
    networks:
      - pong
    restart: always
    volumes:
      - ./client-pong:/app:delegated
      - /app/node_modules
    environment:
      - CHOCKIDAR_USEPOLLING=true

networks:
  pong:
    driver: bridge
