services:
  #
  # Django + Channels (Daphne) - Porta 8000 interna
  #
  web:
    build: ./server-pong
    command: daphne -b 0.0.0.0 -p 8000 setup.asgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=setup.settings
    volumes:
      - ./server-pong:/app
      - ./server-pong/staticfiles:/app/staticfiles
      - ./server-pong/certs:/app/certs
      - ./server-pong/media:/app/media
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  #
  # React (Vite) - Porta 3000 interna
  #
  frontend:
    build:
      context: ./client-pong
      target: development
    volumes:
      - ./client-pong:/app
      - /app/node_modules
    expose:
      - "3000"
    depends_on:
      - web

  #
  # Nginx - Porta 443 com SSL
  #
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server-pong/certs:/etc/nginx/certs
      - ./server-pong/staticfiles:/app/staticfiles
      - ./server-pong/media:/app/media
    ports:
      - "443:443"
    depends_on:
      - web

  #
  # Banco de Dados PostgreSQL
  #
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  #
  # Redis para Channels
  #
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
