# Generated by Django 5.1.3 on 2024-11-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_management',
        ),
    ]
