# Generated by Django 5.1.3 on 2024-12-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_user_is_active_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
