# Generated by Django 5.1.3 on 2024-12-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
