# Generated by Django 5.1.3 on 2025-02-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_language',
            field=models.CharField(choices=[('pt_BR', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español')], default='pt_BR', max_length=5, verbose_name='Idioma atual'),
        ),
    ]
