# Generated by Django 5.1.3 on 2025-01-08 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='type',
        ),
        migrations.AddField(
            model_name='playeralias',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('paused', 'Paused'), ('completed', 'Completed'), ('disconnected', 'Disconnected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchstatus',
            name='event_type',
            field=models.CharField(choices=[('disconnect', 'Disconnect'), ('reconnect', 'Reconnect'), ('lag', 'Lag')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matchstatus',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playeralias',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_aliases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to='game.playeralias'),
        ),
        migrations.AlterUniqueTogether(
            name='playeralias',
            unique_together={('user', 'tournament')},
        ),
    ]
