# Generated by Django 5.1.3 on 2025-01-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_player1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_player2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
