# Generated by Django 5.1.3 on 2025-02-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_remove_match_winner_match_winner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_tournament_match',
            field=models.BooleanField(default=False),
        ),
    ]
