# Generated by Django 5.1.3 on 2025-02-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_match_last_tournament_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='match',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='player',
        ),
        migrations.DeleteModel(
            name='MatchStatus',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
